FROM ubuntu:20.04

RUN apt-get update -y \
    && apt-get install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu g++-aarch64-linux-gnu
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y git cmake

RUN mkdir /workspace && cd /workspace \
    && git clone https://github.com/mz-automation/libiec61850.git \
    && mkdir libiec61850/build
COPY linux-arm64-toolchain.cmake /workspace/libiec61850/build

RUN cd /workspace/libiec61850/build \
    && cmake -G"Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=linux-arm64-toolchain.cmake .. ${1+"$@"} \
    && make -j 2 \
    && make install


WORKDIR /workspace/libiec61850/build